### ISSUE TITLE
Sites not loading because of DPI protection, DNS-over-Quick and VPN exclusions

### ISSUE THREAD

**Issue by antek821** [AdguardTeam/VpnLibs#23]
### Issue Details

- **AdGuard VPN version:**
2.0 (154)
- **AdGuard for Android version:**
3.6.8 (46)
- **VPN mode:**
Compatibility Mode
- **Device:**
Redmi Note 7
- **Operating system and version:**
Android 10
- **Root access:**
No

### Expected Behavior

I would like the sites to work without problems with the settings I described

### Actual Behavior

Adguard blocks sites in the specific case of using Adguard products.. Steps to reproduce in "Additional Information" section

### Additional Information

To reproduce problem we need 3 Adguard products: Adguard for Android, Adguard VPN for Android and Adguard DNS

1. Adguard for Android: we must enable DPI protection and use Adguard DNS - public or private, very important: must use DNS over Quick protocol
2. Adguard VPN for Android:
-connect to any server and run simultaneously with Adguard for Android in Compatibility Mode
-use latest feature: Exclusions 2.0, and choose e.g. Google from Search engine category
3. Open browser (i've tested on Chrome) and try open site added to VPN exclusion from second step: google.com. And here's the problem: site is not loading.
I checked a few other sites from Exclusions 2.0 list: Yahoo, Facebook, LinkedIn and after activate exclusion for them the problem also occurs

I don't know which one exactly Adguard product has a bug, because you only need to do one of three things, the problem is gone:
1. Choose in Adguard for Android settings DNS server with protocol other than DoQ
2. Disable DPI protection
3. Delete exclusion from Adguard VPN

**Comment by maxikuzmin** [comment]
@antek821 I can't reproduce this error.
To troubleshoot, we need to get additional logs from both applications.

Here's what we need to do for Adguard:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
4. Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

Here's what we need to do for Adguard VPN:

1. Open AdGuard VPN app settings;
2. Advanced settings --> Logging level --> Extended;
3. Reproduce the issue and remember the exact time it happened;
4. Open Support --> Export logs and system info;
5. Send the archive to devteam@adguard.com and mention this issue number in the subject.

**Comment by antek821** [comment]
@maxikuzmin I sent an email with the logs you asked for. Please give me feedback if you manage to settle anything on this matter

**Comment by maxikuzmin** [comment]
@antek821 what is the error when loading the site? try the same steps, excluding all third-party DNS filters that you have installed

**Comment by antek821** [comment]
@maxikuzmin This time I used public Adguard DNS server without filtering (but still DNS-over-QUIC) and disable DNS filtering option in Adguard for Android. And I still get the same error in the browser: ERR_TIMED_OUT

Tried the same setup and followed the same steps on another Xiaomi phone and reproduce this problem.

If you trying to reproduce this bug, please switch off and after few moments switch on protection in main view on Adguard for Android. Sometimes it's required to "reset" all settings at this way  on my device.

**Comment by maxikuzmin** [comment]
@antek821  we are not able to reproduce this problem.

It is possible that your error is related to the browser itself. Does it repeat in other browsers? 

Let's try a few steps:

- Clear your browser data
- Reset Chrome to factory defaults
- Reinstall Google Chrome 

If the error still repeats, could you repeat the error and send us the logs? 

Here's what we need you to do:

Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by antek821** [comment]
@maxikuzmin Yes, the problem also occurs in other browsers. I checked e.g.  Firefox, Opera Mini, Vivaldi.

I followed the steps you asked for and sent both files to the e-mail address you provided

**Comment by antek821** [comment]
Maybe it's some other settings that interfere with DPI protection, or the problem occurs only on my Xiaomi devices?

If you don't see anything in the logs, and you have no ideas what the problem could be, just close this issue.

**Comment by maxikuzmin** [comment]
@antek821 we are still dealing with your problem. We'll let you know the result later.

**Comment by maxikuzmin** [comment]
@antek821 we found out that DPI + exclusions have nothing to do with it.

To troubleshoot this issue, we need to get additional logs both apps.

Here's what we need you to do:

AdGuard:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

AdGuard VPN

- Open AdGuard VPN app settings;
- Advanced settings --> Logging level --> Extended;
- Reproduce the issue and remember the exact time it happened;
- Open Support --> Export logs and system info;
- Send the archive to devteam@adguard.com and mention this issue number in the subject.

**Comment by antek821** [comment]
I already sent logs from both applications.

I think the problem is on my ISP's side. When I try to reproduce the problem on e.g. mobile/cellular data instead of wifi, everything works without problems.

I'm closing this issue for the moment. If I find any specific reason for this error, I will get back to you.

Thanks for your help

**Comment by maxikuzmin** [comment]
@antek821 оkay, let me know if you have any questions
