### ISSUE TITLE
Timing out DNS upstream leads to MANY requests pending

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/VpnLibs#40]
After reconnect, these requests are sent to upstream. 

Then due to some reason ngtcp2: ERR_DRAINING is received, and all this hundred requests fail.

**Comment by Batman2814** [comment]
Will this be fix in the stable version of AdGuard for Android as a hot fix because I have noticed that loading webpages will not upload pages where i have to turn off and then on AdGuard in order for it work. I think this is the same issue that I'm having as reported here. but let know if I'm wrong so I can create a new separate issue?
