### ISSUE TITLE
Broken internet connection with Dr.Web

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/VpnLibs#45]
### Issue Details
1. Install Dr.Web (Security space in my case)
2. Install the latest version of Adguard VPN
3. Reboot your system
4. Open browser

### Expected Behavior

No internet connection issues
### Actual Behavior

Webpage doesn't load
### Screenshots

<details><summary>Screenshot:</summary>

![](https://uploads.adguard.com/up85_x4mmy.png)

</details>

**Comment by ngorskikh** [comment]
I'm assuming that this is a Windows issue.

The only way to fix this is to add an exception for AdGuardVpnSvc to Dr. Web, like this:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/57908117/229518779-efc9a817-6138-43b3-a982-b2b788db37aa.png">

Alternatively, one can wait until the Windows team implements WinTun mode and use that.

The issue is that Dr. Web seems to be using a kernel module to redirect traffic at the transport layer to a local proxy process called `dwnetfilter.exe`, which then makes outbound connections (which is the same exact approach used by the VPN service on Windows). Connections made by the VPN service get redirected to `dwnetfilter.exe`, which then makes a connection, which gets redirected to the VPN service, resulting in an infinite loop. However, if you add a VPN exception for `dwnetfilter.exe`, then no traffic will go through the VPN at all, since all traffic is routed through `dwnetfilter.exe`. Therefore, the only way to break the infinite loop is to exclude the VPN service from being filtered through `dwnetfilter.exe`.
